services:
  db:
    image: postgres:16
    container_name: notes-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notessecret
      POSTGRES_DB: notes_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
